### ISSUE TITLE
[QUESTION]f.yml如何配置一个域名关联多个服务/只覆盖特定path而是全部

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1078]
我的需求是
- /* => 云函数A
- /api/* => 云函数B

下面是我云函数A的配置表

```
service: we-mp-admin-web

provider:
  name: aliyun ## 发布的云平台，aliyun，tencent 等

deployType: static

custom:
  customDomain:
    domainName: cps-admin.pmlife.work

package:
  include:
    - build ## 需要拷贝的目录
  exclude:
    - package-lock.json ## 忽略 package-lock.json 文件
    - yarn.lock


```

只能设置`domainName`，所以最后只设置了
- /* => 云函数A

我的需求
- 可以设置特定的path，且不影响到原有设置
- 其他方式解决需求

目前临时的做法
- 每次deploy后，去阿里云函数后台手动重新设置自定义域名，很繁琐
