### ISSUE TITLE
[Question]deployType.config.rewrite如何写排除的正则？

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1129]
需求
- 前端路由模式是history
配置是
```
deployType:
  type: static
  config:
    rootDir: build/web ## 托管目录变为 public
    rewrite:
      /(.*): /index.html
```
这样写的问题是所有的文件都指向了index.html，包括index.js和index.css

然后我想通过正则去写排除
```
      /((?!static).*): /index.html
```

但是这样的结果是直接的报错

```
{
errorMessage: "Invalid regular expression: /^\/\((?\!static)\.\*\)(?:\/)?$/: Invalid group",
errorType: "SyntaxError",
stackTrace: [
"at RegExp (null:null:null)",
"at tokensToRegExp (/code/node_modules/_path-to-regexp@2.4.0@path-to-regexp/index.js:346:10)",
"at stringToRegexp (/code/node_modules/_path-to-regexp@2.4.0@path-to-regexp/index.js:288:10)",
"at pathToRegexp (/code/node_modules/_path-to-regexp@2.4.0@path-to-regexp/index.js:370:10)",
"at rewrite (/code/node_modules/_koa-rewrite@3.0.1@koa-rewrite/index.js:26:14)",
"at beforeRuntimeStart (/code/node_modules/_@midwayjs_static-layer@2.11.2@@midwayjs/static-layer/index.js:48:19)",
"at handlerInvokerWrapper (/code/node_modules/_@midwayjs_runtime-engine@2.11.2@@midwayjs/runtime-engine/dist/runtime.js:209:31)",
"at runtimeStart (/code/node_modules/_@midwayjs_runtime-engine@2.11.2@@midwayjs/runtime-engine/dist/runtime.js:27:20)",
"at ready (/code/node_modules/_@midwayjs_runtime-engine@2.11.2@@midwayjs/runtime-engine/dist/engine.js:54:40)",
"at processTicksAndRejections (internal/process/task_queues.js:97:5)"
]
}

```

所以不知道要怎么写了

**Comment by czy88840616** [comment]
`/[^(asstes)]` 或者 `/^\/(static)/`

**Comment by xmsz** [comment]
- /[^(static)]
- /^\/(static)/
- /[^(static)](.*)

![image](https://user-images.githubusercontent.com/5879146/124208833-ffab9680-db1a-11eb-927b-1123a11a214c.png)

都不行，没有报错了，但其他页面没有指向index.html



需求
- 除了static目录其他都指向/index.html

**Comment by czy88840616** [comment]
我发现 rewrite 不支持排他，我构造了语法，发了个 beta，你可以这样写。

```yaml
deployType: 
  type: static
  config:
    rootDir: build
    rewrite:
      '@not /static/(.*)': /index.html

```

package.json 里先用 beta

```json
  "dependencies": {
    "@midwayjs/static-layer": "beta"
  },
```
