### ISSUE TITLE
midwayjs/koa项目，运行depoly成功，阿里云后台没有添加应用

### ISSUE THREAD

**Issue by 1018715564** [midwayjs/midway#1293]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

已经按照官方的部署教程部署成功，但是阿里云后台没有对应的应用产生。请问详细步骤是什么，accesstoken啥的都是对的

**Comment by czy88840616** [comment]
部署成功那意味着肯定创建了，检查平台上发布的区域。

**Comment by 1018715564** [comment]
ok感谢

**Comment by 1018715564** [comment]
![image](https://user-images.githubusercontent.com/35763284/133382939-5313efd5-5a2c-4a79-b371-abd0e044be4a.png)

index.js入口函数报错

```
  "dependencies": {
    "@midwayjs/bootstrap": "^2.3.0",
    "@midwayjs/core": "^2.3.0",
    "@midwayjs/decorator": "^2.13.2",
    "@midwayjs/koa": "^2.3.0",
    "koa-bodyparser": "^4.3.0"
  },
  "devDependencies": {
    "@midwayjs/cli": "^1.0.0",
    "@midwayjs/luckyeye": "^1.0.0",
    "@midwayjs/mock": "^2.3.0",
    "@types/jest": "^26.0.10",
    "@types/koa-bodyparser": "^4.3.0",
    "@types/node": "^14.17.16",
    "cross-env": "^6.0.0",
    "jest": "^26.4.0",
    "mwts": "^1.0.5",
    "ts-jest": "^26.2.0",
    "typescript": "^4.0.0"
  },
```

**Comment by 1018715564** [comment]
部署到云之后出现这个错误的

**Comment by echosoar** [comment]
我看下，是在 f.yml 中使用 deployType: koa 部署的吗？

**Comment by 1018715564** [comment]
嗯嗯对的

```
service: project-template-app-api ## 应用发布到云平台的名字，一般指应用名

provider:
  name: aliyun ## 发布的云平台，aliyun，tencent 等

custom:
  customDomain:
    domainName: auto

deployType: koa ## 部署的应用类型

```
