### ISSUE TITLE
生产环境如何映射配置文件

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#1593]
我现在遇到一个情况，在进行 docker 镜像构建的时候， src 目录下是不包含 config.prod.ts 文件，这个文件是在生产服务器使用 docker-compose 编排时才 cp 进去，导致 dist 目录下不会再编译生产对应的 config.prod.js 文件，从而无法获取生产配置，请问有什么好的解决方案吗？
dockerFile
```
FROM node:14 AS build

WORKDIR /home

COPY . .

RUN npm install --registry=https://registry.npm.taobao.org

RUN npm run build

FROM node:14.17.3-alpine3.14

WORKDIR /home

COPY --from=build /home/dist ./dist
COPY --from=build /home/bootstrap.js ./
COPY --from=build /home/package.json ./

RUN apk add --no-cache tzdata

ENV TZ="Asia/Shanghai"

RUN npm install pm2 -g

RUN npm install --production

EXPOSE 8001

ENTRYPOINT ["npm", "run", "online"]
```

docker-compose.yaml
```yaml
version: '2'
services:
  lotus_gateway:
    image: lotus_gateway_test:edd31543be2d24887eb70395225fa81a92cf603f
    container_name: lotus_gateway_test
    restart: unless-stopped
    ports:
      - 17001:8001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/config.prod.ts:/home/dist/config/config.prod.ts
    env_file:
      - ./.env
```
