### ISSUE TITLE
Midway 3.0 怎么能部署到 aws lambda ？

### ISSUE THREAD

**Issue by zomixi** [midwayjs/midway#2245]
Midway 3.0 怎么能部署到 aws lambda? 有无文档或者示例？
目前我试了 `f.yml` provider 为 `aws` 时 deploy 无作用。
![image](https://user-images.githubusercontent.com/33776415/185027709-bfaf083e-9d79-4ac9-996f-d5d47b4c7813.png)

**Comment by czy88840616** [comment]
暂不支持 aws。

**Comment by zomixi** [comment]
https://www.npmjs.com/package/@midwayjs/serverless-aws-starter

**Comment by zomixi** [comment]
`midway-bin package` 打包支持 `aws` 吗

**Comment by czy88840616** [comment]
这个只是启动器，最困难的在于aws cli的适配，这部分没有。

**Comment by zomixi** [comment]
有个项目是 midway+eggjs，已经部署在aliyun FC。现在想在 aws 也部署一套，有什么好办法吗？

**Comment by czy88840616** [comment]
可以通过 midway-bin package 之后，进入 .serverless 目录使用 aws 的工具进行发布 https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html

**Comment by zomixi** [comment]
provider 是 aws 时打包产物没有 starter。打包 aliyun 时是有 starter 的。
```yml
service: cloud-service ## 应用发布到云平台的名字

provider:
  name: aws ## 发布的云平台，aliyun，tencent 等

aggregation: ## 对 HTTP 函数使用聚合模式部署
  cloud-server: ## 部署的函数名
    deployOrigin: false # 是否部署原始方法
    functionsPattern: ## 匹配的函数规则
      - '*'

package:
  exclude:
    - package-lock.json ## 忽略 package-lock.json 文件
```
