### ISSUE TITLE
如何保证本地环境用的config.local不打包进dist目录？

### ISSUE THREAD

**Issue by iwege** [midwayjs/midway#537]
# 问题
无法将`config.local.*`文件排除在dist目录之外

# 期望
本地测试使用到的配置文件不上传到云端

# 复现步骤
1. 创建 `src/config/config.local.ts`
2. 创建`f.yml`内容如下：
```yml
service: serverless-hello-world

provider:
  name: aliyun # cloud platform name

functions:
  index: # functionName
    handler: index.handler # handler name
    events: # function events
      - http:
          method: post

package:
  exclude:
    - src/config/config.local.ts
    - .serverless/dist/config/config.local.js
    - .serverless/dist/config/config.local.d.ts
    - dist/config/config.local.js
    - dist/config/config.local.d.ts
  artifact: code.zip
## complete yml definition, see: https://www.yuque.com/midwayjs/faas/serverless_yml

```

3. 运行`f package && unzip code.zip -d code && ls code/dist/config`
4. 打包的文件里面依旧存在config.local.js

**Comment by czy88840616** [comment]
```yaml
package:
  exclude:
    - '**/*.local.ts'
```
