### ISSUE TITLE
发布到腾讯云scf直接多个path

### ISSUE THREAD

**Issue by zhangyuang** [midwayjs/midway#633]
# 示例

需要支持以下功能能够将多个path打到同一个函数。根据现象在阿里云已经支持，但是腾讯云不支持。
```yml
functions:
  index:
    handler: index.handler
    render:
        mode: ssr
    events:
      - http:
          path: /
          method: get
      - http:
          path: /detail/*
          method: get
```

## 原因定位

通过观察使用聚合函数发布的功能生成的最终文件，并没有包含多path场景下除了第一个path之后的path。
![image](https://user-images.githubusercontent.com/17424434/92727862-60a68a00-f3a2-11ea-8474-55fab0650738.png)
