### ISSUE TITLE
OSS触发器配置失败

### ISSUE THREAD

**Issue by SoundShell** [midwayjs/midway#744]
```
captureVideoOSSEvent:
    handler: captureVideoOSSEvent.handler
    concurrency: 10
    events:
      - oss:
          bucket: ${env.BUCKET}
          events:
            - oss:ObjectCreated:PutObject
          filter:
            prefix: video/video/videoCapture/
            suffix: .mp4
          role: 'acs:ram::*:role/*'
          version: ${env.VERSION}
```

message: event source 'oss' returned error: Cannot specify overlapping prefix and suffix with same event type..
